# Generated by Django 5.2.6 on 2025-10-09 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('prevision', models.CharField(max_length=100)),
                ('usuarios_id_usuario', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id_ficha', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('notas', models.TextField(blank=True, null=True)),
                ('hora_ficha', models.TimeField(blank=True, null=True)),
                ('direccion_paciente', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_paciente', models.CharField(blank=True, max_length=15, null=True)),
                ('rut_paciente', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_paciente', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paciente', models.CharField(blank=True, max_length=50, null=True)),
                ('prevision_paciente', models.CharField(blank=True, max_length=100, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appvaleria.paciente')),
            ],
        ),
    ]
