# Generated by Django 5.2.6 on 2025-10-17 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id_ficha', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('notas', models.TextField(blank=True, null=True)),
                ('hora_ficha', models.DateTimeField(blank=True, null=True)),
                ('direccion_paciente', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_paciente', models.CharField(blank=True, max_length=15, null=True)),
                ('rut_paciente', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_paciente', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paciente', models.CharField(blank=True, max_length=50, null=True)),
                ('prevision_paciente', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ficha_medica',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=15, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('prevision', models.CharField(max_length=100, verbose_name='Previsión')),
                ('usuarios_id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
