# Generated by Django 5.2.6 on 2025-10-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appvaleria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='prevision',
            field=models.CharField(blank=True, max_length=100, verbose_name='Previsión'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuarios_id_usuario',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del usuario (opcional)'),
        ),
    ]
