# Generated by Django 5.2.7 on 2025-10-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appvaleria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='usuarios_id_usuario',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del usuario (opcional)'),
        ),
    ]
