# Generated by Django 5.2.7 on 2025-10-13 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appvaleria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamedica',
            name='hora_ficha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appvaleria.paciente'),
        ),
        migrations.AlterModelTable(
            name='fichamedica',
            table='ficha_medica',
        ),
    ]
