# Generated by Django 5.2.6 on 2025-10-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appvaleria', '0002_alter_paciente_apellido_alter_paciente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
    ]
