# Generated by Django 5.2.7 on 2025-10-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appvaleria', '0002_alter_paciente_usuarios_id_usuario'),
        ('Appvaleria', '0004_alter_paciente_email'),
    ]

    operations = [
    ]
