# Generated by Django 5.2.7 on 2025-10-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appvaleria', '0005_merge_20251020_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
    ]
