# Generated by Django 5.2.6 on 2025-11-12 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appvaleria', '0006_alter_paciente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id_cita', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateField(verbose_name='Fecha de la cita')),
                ('hora_cita', models.TimeField(verbose_name='Hora de la cita')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo de la consulta')),
                ('estado', models.CharField(choices=[('Confirmada', 'Confirmada'), ('En espera', 'En espera'), ('Anulada', 'Anulada')], default='En espera', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='Appvaleria.paciente')),
            ],
            options={
                'db_table': 'citas_medicas',
                'ordering': ['fecha_cita', 'hora_cita'],
            },
        ),
    ]
