# Generated by Django 5.2.6 on 2025-10-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoraAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('razon', models.TextField(max_length=300)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
            ],
        ),
    ]
