# Generated by Django 5.2.6 on 2025-10-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoraAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('razon', models.CharField(max_length=300)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_secretaria', models.CharField(max_length=15, unique=True)),
                ('nombre_secretaria', models.CharField(max_length=50)),
                ('apellido_secretaria', models.CharField(max_length=50)),
                ('email_secretaria', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('usuarios_id_usuario', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'secretaria',
            },
        ),
    ]
