# Generated by Django 5.2.7 on 2025-10-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appclaudio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaagendada',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='horaagendada',
            name='hora',
        ),
        migrations.AddField(
            model_name='horaagendada',
            name='hora_final',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='horaagendada',
            name='hora_inicio',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AlterField(
            model_name='horaagendada',
            name='razon',
            field=models.CharField(max_length=300),
        ),
    ]
