# Generated by Django 5.2.6 on 2025-11-15 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appclaudio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horaagendada',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horas_agendadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='usuarios_id_usuario',
            field=models.ForeignKey(blank=True, db_column='usuarios_id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretarias', to=settings.AUTH_USER_MODEL),
        ),
    ]
