# Generated by Django 5.2.6 on 2025-10-16 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appclaudio', '0002_remove_horaagendada_estado_remove_horaagendada_hora_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horaagendada',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horaagendada',
            name='hora_final',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horaagendada',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
