# Generated by Django 5.2.6 on 2025-10-16 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appclaudio', '0003_horaagendada_usuario_alter_horaagendada_hora_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaagendada',
            name='usuario',
        ),
    ]
